### ISSUE TITLE
Refactoring ideas

### ISSUE THREAD

**Issue by leekelleher** [mzajkowski/umbraco-backoffice-themes#1]
Hey @mzajkowski!

I have a bunch of ideas with this, but didn't want to go ahead and refactor things without checking with you first.

Here are some of my (opinionated) thoughts...

- Rename the folder from "`~/App_Plugins/Our.Umbraco.BackofficeThemes`" to "`~/App_Plugins/BackofficeThemes`", (the previous is quite long).
- Each "theme" should be a separate CSS file, (not using a specific `class` in a shared stylesheet).
- `theming.js` should be an Angular controller for the dashboard, (currently all the functions are globally declared).
- Have a separate JS to load in the selected theme CSS - reading from the cookie value.

I'm happy to send a PR over for any (or all) of these.

**Comment by mzajkowski** [comment]
Hey @leekelleher!

Lightning speed 🌩️ :)

I fully agree with all the suggested refactoring ideas. Having separated stylesheets might give us advantage at some point to tailor them to specific versions and even build separated files for v7 and v8.

I'm more than happy then to merge your PR. Thanks!

H5YR!
