### ISSUE TITLE
Enhancement - stylable template/files to be supplied

### ISSUE THREAD

**Issue by jonrandahl** [mzajkowski/umbraco-backoffice-themes#8]
Any chance of actually getting a generic dashboard with the main back office UI element exposed?

While I'm happy to spin up a new instance of Umbraco for this, it would be a great help if the themes could be developed on all platforms?

Also found these links about a style guide for the back office which can help guide us when needed:

 - https://our.umbraco.org/forum/umbraco-7/developing-umbraco-7-packages/69278-style-guides
 - https://our.umbraco.org/forum/templates-partial-views-and-macros/84610-frontend-style-guides-pattern-libraries-component-libraries
 - https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/README.md

Open to suggestions!

**Comment by mzajkowski** [comment]
I don't know if I understand you correctly, so.. correct me if I'm wrong :)

You mean the dashboard/section with "demo" of the theme being applied or a dashboard which is already in the package, but wasn't automatically added to the Umbraco (see #9 where it's fixed already)?

**Comment by jonrandahl** [comment]
No, sorry @mzajkowski, with the `dashboard` reference I meant to have a style guide in place as part of the repo which would allow theme developers to know they've themed all the right parts via the right selectors - hence the links to previous conversations about this very topic.

If all goes as planned then this repo could become just that - the guide to styling the [Umbraco](https://github.com/umbraco) back office!

**Comment by mzajkowski** [comment]
That would be amazing @jonrandahl!

Something like Bootstrap's component's demos: https://getbootstrap.com/docs/4.1/components/alerts/ with dropdown to change the theme on it :) #dreaming

**Comment by jonrandahl** [comment]
exactly but more of a single page like this:

https://codepen.io/guide

as it makes things easier.

**Comment by jonrandahl** [comment]
Closing as stale. Hope all is well with everyone! #h5yr!
